configfile: "workflow/config/pipeline.yaml"
rawdata = Path(config["directories"]["rawdata"])
procdata = Path(config["directories"]["procdata"])
metadata = Path(config["directories"]["metadata"])
results = Path(config["directories"]["results"])
logs = Path(config["directories"]["logs"])

include: "rules/metadata.smk"
include: "rules/treatmentResponse.smk"
include: "rules/rnaseq.smk"
include: "rules/cnv.smk"


version = config["GDSC_version"]
release = config["GDSC_release"]

rule build_Pharmacoset:
    input:
