##################################################################
# Configuration file for the GDSC PIPELINE
# The following lines are specific to each pipeline run
# namely, the dataset name, version, release, and the directories
name: "DATASET_NAME"                  # Name of the dataset, i.e GDSC, CCLE, CTRP, NCI60
description: "The Genomics of Drug Sensitivity in Cancer (GDSC) is ...
  This dataset contains molecular profiles for 1,000 cancer cell lines, 
  and drug sensitivity data against a wide range of anti-cancer therapeutics."
url: "https://www.cancerrxgene.org/"
GDSC_version: "GDSC2"                     # Version of the dataset, i.e GDSC1 GDSC2
GDSC_release: 8.4

directories:
  rawdata: "rawdata"                      # Directory for raw data
  procdata: "procdata"                    # Directory for processed data
  metadata: "metadata"                    # Directory for metadata
  results: "results"                      # Directory for results
  logs: "logs"                            # Directory for logs

##################################################################
# DATA SOURCES BELOW
metadata:
  treatmentMappingFile:
    description: "BHKLAB curated mapping file between GDSC and standardized treatment ID names."
    url: "https://raw.githubusercontent.com/BHKLAB-DataProcessing/Annotations/master/drugs_with_ids.csv"
  sampleMappingFile:
    description: "BHKLAB curated mapping file between GDSC and standardized sample ID names."
    url: "https://raw.githubusercontent.com/BHKLAB-DataProcessing/Annotations/master/cell_annotation_all.csv"
  GDSC_to_CCLE:
    treatmentMappingFile:
      description: "Set of overlapping cell-lines between the GDSC1000 and CCLE screens (Barretina et al, Nature 2012)"
      url: "https://www.cancerrxgene.org/gdsc1000/GDSC1000_WebResources//Data/suppData/TableS4F.xlsx"
    sampleMappingFile:
      description: "Set of overlapping drugs between our study and CCLE (Barretina et al, Nature 2012)"
      url: "https://www.cancerrxgene.org/gdsc1000/GDSC1000_WebResources//Data/suppData/TableS4E.xlsx"
  referenceGenome:
    description: "Ensembl Release v91 as described in https://depmap.sanger.ac.uk/documentation/datasets/gene-annotation-mapping/"
    species: "homo_sapiens"
    release: "91"
    build: "GRCh38"
  '8.2':
    sampleMetadata: 
      description:
      url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.2/Cell_Lines_Details.xlsx"
    treatmentMetadata:
      description:
      url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.2/screened_compunds_rel_8.2.csv"
  '8.4':
    sampleMetadata: 
      description:
      url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.4/Cell_Lines_Details.xlsx"
    treatmentMetadata:
      description:
      url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.4/screened_compounds_rel_8.4.csv"
  '8.5':
    sampleMetadata: 
      description:
      url: "https://cog.sanger.ac.uk/cancerrxgene/GDSC_release8.5/Cell_Lines_Details.xlsx"
    treatmentMetadata:
      description:
      url: "https://cog.sanger.ac.uk/cancerrxgene/GDSC_release8.5/screened_compounds_rel_8.5.csv"

treatmentResponse:
  '8.2':
    date: "25Feb20"
    GDSC1:
      rawdata:
        description: "The raw data for the GDSC1 release 8.2 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.2/GDSC1_public_raw_data_25Feb20.csv"
      processed:
        description: "The processed data for the GDSC1 release 8.2 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.2/GDSC1_fitted_dose_response_25Feb20.xlsx"
    GDSC2:
      rawdata:
        description: "The raw data for the GDSC2 release 8.2 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.2/GDSC2_public_raw_data_25Feb20.csv"
      processed:
        description: "The processed data for the GDSC2 release 8.2 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.2/GDSC2_fitted_dose_response_25Feb20.xlsx"
  '8.4':
    date: "24Jul22"
    GDSC1:
      rawdata:
        description: "The raw data for the GDSC1 release 8.4 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.4/GDSC1_public_raw_data_24Jul22.csv"
      processed:
        description: "The processed data for the GDSC1 release 8.4 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.4/GDSC1_fitted_dose_response_24Jul22.xlsx"
    GDSC2:
      rawdata:
        description: "The raw data for the GDSC2 release 8.4 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.4/GDSC2_public_raw_data_24Jul22.csv"
      processed:
        description: "The processed data for the GDSC2 release 8.4 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.4/GDSC2_fitted_dose_response_24Jul22.xlsx"
  '8.5': 
    date: "27Oct23"
    GDSC1:
      rawdata:
        description: "The raw data for the GDSC1 release 8.5 is available from the GDSC website."
        url: "https://cog.sanger.ac.uk/cancerrxgene/GDSC_release8.5/GDSC1_public_raw_data_27Oct23.csv"
      processed:
        description: "The processed data for the GDSC1 release 8.5 is available from the GDSC website."
        url: "https://cog.sanger.ac.uk/cancerrxgene/GDSC_release8.5/GDSC1_fitted_dose_response_27Oct23.xlsx"
    GDSC2:
      rawdata:
        description: "The raw data for the GDSC2 release 8.5 is available from the GDSC website."
        url: "https://cog.sanger.ac.uk/cancerrxgene/GDSC_release8.5/GDSC2_public_raw_data_27Oct23.csv"
      processed:
        description: "The processed data for the GDSC2 release 8.5 is available from the GDSC website."
        url: "https://cog.sanger.ac.uk/cancerrxgene/GDSC_release8.5/GDSC2_fitted_dose_response_27Oct23.xlsx"

molecularProfiles:
  cellModelPassports:
    sampleAnnotation: 
      description: "A list of all models in the Cell Model Passports with their annotation including tissue, cancer type and identifiers."     
      url: "https://cog.sanger.ac.uk/cmp/download/model_list_latest.csv.gz"
    geneAnnotation:
      description: "A list of all genes used in the Cell Model Passports, with HUGO, Ensembl, Entrez and Refseq annotation."
      url: "https://cog.sanger.ac.uk/cmp/download/gene_identifiers_latest.csv.gz"
  
  rnaseq:
    rawdata:
      description: "Data available from EGA under accession EGAD00001001357. 466 samples. Access to raw cram files requires DAC approval. NOTE: This data is not yet used in the pipeline"
      url: "https://ega-archive.org/datasets/EGAD00001001357"
    processed:
      description: "Read counts, TPM & FPKM-values for all sequenced models including cell lines and organoids."
      tool: TODO::(add tool)
      tool_version: TODO::(add tool version)
      url: "https://cog.sanger.ac.uk/cmp/download/rnaseq_all_20220624.zip"

  cnv:
    WES_CNV: 
      description: "Total copy number and categorical CNA calls derived from WES data processed through PureCN."
      tool: TODO::(add tool)
      tool_version: TODO::(add tool version)
      url: "https://cog.sanger.ac.uk/cmp/download/WES_pureCN_CNV_genes_20221213.zip"  

  mutation:
    WGS_VCF: 
      description: "Caveman and Pindel processed VCFs with cancer driver annotation."
      tool: TODO::(add tool)
      tool_version: TODO::(add tool version)
      url: "https://cog.sanger.ac.uk/cmp/download/mutations_wgs_vcf_20221123.zip"
    WES_VCF: 
      description: "Caveman and Pindel processed VCFs with cancer driver annotation."
      tool: TODO::(add tool)
      tool_version: TODO::(add tool version)
      url: "https://cog.sanger.ac.uk/cmp/download/mutations_wes_vcf_20221010.zip"
    all_mutations: 
      description: "A list of all mutations present in all sequenced models."
      tool: TODO::(add tool)
      tool_version: TODO::(add tool version)
      url: "https://cog.sanger.ac.uk/cmp/download/mutations_all_20230202.zip"
    Genes_Metadata:
      description: "The cancer driver gene list used by the Cell Model Passports"
      tool: TODO::(add tool)
      tool_version: TODO::(add tool version)
      url: "https://cog.sanger.ac.uk/cmp/download/driver_mutations_20221208.csv"

  fusion:
    gene_fusions:
      description: TODO::(add description)
      tool: TODO::(add tool)
      tool_version: TODO::(add tool version)
      url: "https://cog.sanger.ac.uk/cmp/download/Fusions_20230725.zip"

  microarray:
    description: "Data taken from https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-3610/." 
    metadata_tsv: 
      description: TODO::(add description)
      url: "https://www.ebi.ac.uk/biostudies/files/E-MTAB-3610/E-MTAB-3610.tsv"
    metadata_srdf: 
      description: TODO::(add description)
      url: "https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/610/E-MTAB-3610/Files/E-MTAB-3610.sdrf.txt"
    metadata_json: 
      description: TODO::(add description)
      url: "https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/610/E-MTAB-3610/Files/raw-data_filelist.json"
    processed: 
      description: "RMA normalised basal expression profiles for all the cell-lines. https://www.cancerrxgene.org/gdsc1000/GDSC1000_WebResources/Home.html"
      tool: TODO::(add tool)
      tool_version: TODO::(add tool version)
      url: "https://www.cancerrxgene.org/gdsc1000/GDSC1000_WebResources///Data/preprocessed/Cell_line_RMA_proc_basalExp.txt.zip"
  